// Generated by CoffeeScript 1.3.3
(function() {
  var LocalStorage, fs;

  LocalStorage = require('../').LocalStorage;

  fs = require('fs');

  exports.LocalStorageTest = {
    testFileExists: function(test) {
      var f;
      fs.writeFileSync('./scratchFile', 'hello', 'utf8');
      f = function() {
        var ls2;
        return ls2 = new LocalStorage('./scratchFile');
      };
      test.throws(f, Error);
      fs.unlinkSync('./scratchFile');
      return test.done();
    }
  };

}).call(this);
