// Generated by CoffeeScript 1.3.3
(function() {
  var LocalStorage;

  LocalStorage = require('../').LocalStorage;

  exports.LocalStorageTest = {
    testLocalStorage: function(test) {
      var a, localStorage, o;
      localStorage = new LocalStorage('./scratch');
      test.equal(localStorage.location, './scratch');
      localStorage.setItem('1', 'something');
      test.equal(localStorage.getItem('1'), 'something');
      o = {
        a: 1,
        b: 'some string',
        c: {
          x: 1,
          y: 2
        }
      };
      localStorage.setItem('2', o);
      test.deepEqual(localStorage.getItem('2'), o.toString());
      a = [
        1, 'some string', {
          a: 1,
          b: 'some string',
          c: {
            x: 1,
            y: 2
          }
        }
      ];
      localStorage.setItem('2', a);
      test.deepEqual(localStorage.getItem('2'), a.toString());
      test.deepEqual(localStorage.keys, ['1', '2']);
      test.equal(localStorage.length, 2);
      localStorage.removeItem('2');
      test.equal(localStorage.getItem('2'), null);
      test.deepEqual(localStorage.keys, ['1']);
      test.equal(localStorage.length, 1);
      test.equal(localStorage.key(0), '1');
      localStorage.clear();
      test.equal(localStorage.length, 0);
      localStorage._deleteLocation();
      return test.done();
    }
  };

}).call(this);
